[colors.primary]
background = '#0d0e14'
foreground = '#cdd6f4'

[colors.selection]
text = '#cdd6f4'
background = '#472e64'

[colors.cursor]
text = '#0d0e14'
cursor = '#cba6f7'

[colors.normal]
black   = '#181920'
red     = '#ff728c'
green   = '#7bf797'
yellow  = '#ffdb72'
blue    = '#b88eea'
magenta = '#4c2d72'
cyan    = '#cba6f7'
white   = '#f6efff'

[colors.bright]
black   = '#9994a0'
red     = '#ff9fb1'
green   = '#a5ffba'
yellow  = '#ffe8a5'
blue    = '#d8b7ff'
magenta = '#dfc4ff'
cyan    = '#ead9ff'
white   = '#fbf8ff'
