
# sub config load
source=./mango-config/env.conf
source=./mango-config/animations.conf
source=./mango-config/bind.conf
source=./mango-config/rule.conf
source=./mango-config/tag.conf

# startup
exec-once=~/.config/mango/autostart.sh

# dms configs
source=./dms/cursor.conf
source=./dms/colors.conf
source=./dms/outputs.conf

