
# sub config load
source=./mango-config/env.conf
source=./mango-config/animations.conf
source=./mango-config/bind.conf
source=./mango-config/rule.conf
source=./mango-config/tag.conf
source=./mango-config/cursor.conf
# startup
exec-once=~/.config/mango/autostart.sh



# This sources the noctalia theme

source = /home/sh4dow/.config/mango/noctalia.conf

