# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x111111ff
bordercolor = 0x606060ff
focuscolor = 0xaaaaaaff
maximizescreencolor = 0xa7a7a7ff
urgentcolor = 0xddddddff
scratchpadcolor = 0xccccccff
globalcolor = 0x5d4545ff
overlaycolor = 0x594242ff
