# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x0a0a12ff
bordercolor = 0x5b5b75ff
dropcolor = 0x8b2e2e80
splitcolor = 0x9a7398ff
focuscolor = 0x8b2e2eff
maximizescreencolor = 0x8baa82ff
urgentcolor = 0xc25b5bff
scratchpadcolor = 0x9a7398ff
globalcolor = 0x3f0d0dff
overlaycolor = 0x315128ff
jump_label_decorate_fg_color = 0xe4ded2ff
jump_label_decorate_bg_color = 0x1c1c2aff
jump_label_decorate_focus_fg_color = 0x1c1c28ff
jump_label_decorate_focus_bg_color = 0x8b2e2eff
jump_label_decorate_border_color = 0x5b5b75ff
