# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x131316ff
bordercolor = 0x928f99ff
dropcolor = 0xc4c2ef80
splitcolor = 0xecb8d6ff
focuscolor = 0xc4c2efff
maximizescreencolor = 0xc7c4d8ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xecb8d6ff
globalcolor = 0x8e8db6ff
overlaycolor = 0x484758ff
jump_label_decorate_fg_color = 0xe5e1e5ff
jump_label_decorate_bg_color = 0x2a292cff
jump_label_decorate_focus_fg_color = 0x2d2d50ff
jump_label_decorate_focus_bg_color = 0xc4c2efff
jump_label_decorate_border_color = 0x928f99ff
