[colors.primary]
background = '#15141b'
foreground = '#edecee'

[colors.cursor]
text = '#15141b'
cursor = '#a277ff'

[colors.vi_mode_cursor]
text = '#15141b'
cursor = '#a277ff'

[colors.search.matches]
foreground = '#29263c'
background = '#ffca85'

[colors.search.focused_match]
foreground = '#29263c'
background = '#a277ff'

[colors.footer_bar]
foreground = '#29263c'
background = '#e4e3e8'

[colors.hints.start]
foreground = '#29263c'
background = '#61ffca'

[colors.hints.end]
foreground = '#29263c'
background = '#61ffca'

[colors.selection]
text = '#edecee'
background = '#29263c'


[colors.normal]
black   = '#110f18'
red     = '#ff6767'
green   = '#61ffca'
yellow  = '#ffca85'
blue    = '#a277ff'
magenta = '#a277ff'
cyan    = '#61ffca'
white   = '#edecee'


[colors.bright]
black   = '#4d4d4d'
red     = '#ff6767'
green   = '#61ffca'
yellow  = '#ffca85'
blue    = '#a277ff'
magenta = '#a277ff'
cyan    = '#61ffca'
white   = '#edecee'


[colors.dim]
black   = '#110f18'
red     = '#ff6767'
green   = '#61ffca'
yellow  = '#ffca85'
blue    = '#a277ff'
magenta = '#a277ff'
cyan    = '#61ffca'
white   = '#edecee'
