[colors.primary]
background = '#131316'
foreground = '#e5e1e5'

[colors.cursor]
text = '#131316'
cursor = '#e5e1e5'

[colors.vi_mode_cursor]
text = '#131316'
cursor = '#c4c2ef'

[colors.search.matches]
foreground = '#47464e'
background = '#ecb8d6'

[colors.search.focused_match]
foreground = '#47464e'
background = '#c4c2ef'

[colors.footer_bar]
foreground = '#47464e'
background = '#e5e1e5'

[colors.hints.start]
foreground = '#47464e'
background = '#c7c4d8'

[colors.hints.end]
foreground = '#47464e'
background = '#c7c4d8'

[colors.selection]
text = '#c8c5cf'
background = '#47464e'


[colors.normal]
black   = '#47464e'
red     = '#ffb4ab'
green   = '#c4c2ef'
yellow  = '#c7c4d8'
blue    = '#ecb8d6'
magenta = '#c4c2ef'
cyan    = '#c7c4d8'
white   = '#e5e1e5'


[colors.bright]
black   = '#928f99'
red     = '#ffb4ab'
green   = '#c4c2ef'
yellow  = '#c7c4d8'
blue    = '#ecb8d6'
magenta = '#c4c2ef'
cyan    = '#c7c4d8'
white   = '#e5e1e5'


[colors.dim]
black   = '#47464e'
red     = '#ffb4ab'
green   = '#c4c2ef'
yellow  = '#c7c4d8'
blue    = '#ecb8d6'
magenta = '#c4c2ef'
cyan    = '#c7c4d8'
white   = '#e5e1e5'
