[colors.primary]
background = '#0a0a12'
foreground = '#e4ded2'

[colors.cursor]
text = '#0a0a12'
cursor = '#e4ded2'

[colors.vi_mode_cursor]
text = '#0a0a12'
cursor = '#8b2e2e'

[colors.search.matches]
foreground = '#14141e'
background = '#9a7398'

[colors.search.focused_match]
foreground = '#14141e'
background = '#8b2e2e'

[colors.footer_bar]
foreground = '#14141e'
background = '#e3e3e8'

[colors.hints.start]
foreground = '#14141e'
background = '#8baa82'

[colors.hints.end]
foreground = '#14141e'
background = '#8baa82'

[colors.selection]
text = '#0a0a12'
background = '#e4ded2'


[colors.normal]
black   = '#1c1c28'
red     = '#c25b5b'
green   = '#8baa82'
yellow  = '#e6c27a'
blue    = '#6270a8'
magenta = '#9a7398'
cyan    = '#95b3b0'
white   = '#f2eadf'


[colors.bright]
black   = '#2a2a38'
red     = '#c25b5b'
green   = '#8baa82'
yellow  = '#e6c27a'
blue    = '#6270a8'
magenta = '#9a7398'
cyan    = '#95b3b0'
white   = '#fff8f2'


[colors.dim]
black   = '#1c1c28'
red     = '#c25b5b'
green   = '#8baa82'
yellow  = '#e6c27a'
blue    = '#6270a8'
magenta = '#9a7398'
cyan    = '#95b3b0'
white   = '#f2eadf'
