[accessibility]
ui_scale = 0.95000000670552254

[bar]
order = ["default", "Sh4dow"]

[bar.Sh4dow]
border = "on_primary"
enabled = false
end = ["media", "tray", "notifications", "network", "volume", "battery"]
font_family = "JetBrainsMono NFM"
margin_edge = 0
margin_ends = 99
position = "bottom"
radius = 80
radius_top_left = 80
radius_top_right = 80
scale = 0.75
start = ["workspaces"]
widget_spacing = 11

[bar.default]
center = ["clock", "activity"]
end = ["media", "tray", "notifications", "network", "volume", "battery"]
font_family = "JetBrainsMono NFM"
margin_edge = 0
margin_ends = 92
position = "right"
radius_bottom_left = 80
radius_bottom_right = 0
radius_top_left = 80
radius_top_right = 0
scale = 0.75
start = ["workspaces", "cat"]
thickness = 34

[calendar]
enabled = true

[desktop_widgets]
enabled = true
schema_version = 2
widget_order = [
  "desktop-widget-0000000000000002",
  "desktop-widget-0000000000000003",
]

[desktop_widgets.grid]
cell_size = 16
major_interval = 4
visible = true

[desktop_widgets.widget.desktop-widget-0000000000000002]
box_height = 288.0
box_width = 304.0
cx = 1139.0
cy = 624.0
output = "eDP-1"
placement_height = 768.0
placement_width = 1366.0
rotation = 0.0
type = "fancy_audio_visualizer"

[desktop_widgets.widget.desktop-widget-0000000000000002.settings]
background = false
background_opacity = 0.35000000000000003
bloom_intensity = 0.60000000000000009
visualization_mode = "wave_rings"

[desktop_widgets.widget.desktop-widget-0000000000000003]
box_height = 160.0
box_width = 384.0
cx = 219.0
cy = 656.0
output = "eDP-1"
placement_height = 768.0
placement_width = 1366.0
rotation = 0.0
type = "media_player"

[desktop_widgets.widget.desktop-widget-0000000000000003.settings]
background = false
font_family = ""
hide_when_no_media = true
layout = "horizontal"

[dock]
auto_hide = true
reserve_space = false
show_running = false

[hot_corners.bottom_left]
action = "window_switcher"

[hot_corners.top_left]
action = "launcher"

[hot_corners.top_right]
action = "control_center"

[idle]
behavior_order = ["lock", "screen-off", "lock-and-suspend"]

[idle.behavior.lock]
action = "lock"
enabled = true
timeout = 600.0

[idle.behavior.lock-and-suspend]
action = "lock_and_suspend"
enabled = true
timeout = 900.0

[idle.behavior.screen-off]
action = "screen_off"
enabled = true
timeout = 660.0

[lockscreen]
fingerprint = false

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
  "lockscreen-login-box@WL-1",
  "lockscreen-login-box@eDP-1",
  "lockscreen-widget-0000000000000001",
  "lockscreen-widget-0000000000000002",
  "lockscreen-widget-0000000000000003",
  "lockscreen-widget-0000000000000004",
  "lockscreen-widget-0000000000000005",
]

[lockscreen_widgets.grid]
cell_size = 8
major_interval = 4
visible = true

[lockscreen_widgets.widget."lockscreen-login-box@WL-1"]
box_height = 196.0
box_width = 720.0
cx = 640.0
cy = 601.0
output = "WL-1"
placement_height = 0.0
placement_width = 0.0
rotation = 0.0
type = "login_box"

[lockscreen_widgets.widget."lockscreen-login-box@WL-1".settings]
background_color = "surface_variant"
background_opacity = 0.88
background_radius = 12.0
center_password_text = false
input_opacity = 1.0
input_radius = 6.0
layout = "regular"
show_caps_lock = true
show_keyboard_layout = true
show_login_button = true
show_media = true
show_session_buttons = true
show_unlock_hint = true
show_weather = true

[lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
box_height = 196.0
box_width = 720.0
cx = 675.0
cy = 654.0
output = "eDP-1"
placement_height = 768.0
placement_width = 1366.0
rotation = 0.0
type = "login_box"

[lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
background_color = "surface_variant"
background_opacity = 0.88
background_radius = 12.0
center_password_text = false
input_opacity = 1.0
input_radius = 6.0
layout = "regular"
show_caps_lock = true
show_keyboard_layout = true
show_login_button = true
show_media = true
show_session_buttons = true
show_unlock_hint = true
show_weather = true

[lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
box_height = 0.0
box_width = 0.0
cx = 653.0
cy = 48.0
output = "eDP-1"
placement_height = 768.0
placement_width = 1366.0
rotation = 0.0
type = "clock"

[lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
background = true
background_color = "surface"
background_opacity = 0.80000000000000004
background_padding = 10
background_radius = 12
center_text = false
circle = true
clock_style = "digital"
color = "on_surface"
font_family = ""
format = "{:%I:%M %p}"
shadow = true

[lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
box_height = 0.0
box_width = 0.0
cx = 653.0
cy = 225.5
output = "eDP-1"
placement_height = 768.0
placement_width = 1366.0
rotation = 0.0
type = "fancy_audio_visualizer"

[lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
background = false

[lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
box_height = 0.0
box_width = 0.0
cx = 657.5
cy = 405.0
output = "eDP-1"
placement_height = 768.0
placement_width = 1366.0
rotation = 0.0
type = "media_player"

[lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
box_height = 0.0
box_width = 0.0
cx = 74.117645263671875
cy = 115.0
output = "eDP-1"
placement_height = 768.0
placement_width = 1366.0
rotation = 0.0
type = "sticker"

[lockscreen_widgets.widget.lockscreen-widget-0000000000000004.settings]
image_path = "/home/sh4dow/Pictures/Pics/boy.jpg"
opacity = 1.0

[lockscreen_widgets.widget.lockscreen-widget-0000000000000005]
box_height = 0.0
box_width = 0.0
cx = 1291.0
cy = 115.0
output = "eDP-1"
placement_height = 768.0
placement_width = 1366.0
rotation = 0.0
type = "sticker"

[lockscreen_widgets.widget.lockscreen-widget-0000000000000005.settings]
image_path = "/home/sh4dow/Pictures/Pics/kiritoAsuna.jpg"
opacity = 1.0

[notification]
background_opacity = 0.69999998435378075
layer = "overlay"
offset_x = 17
scale = 0.75

[plugin_settings."blackbartblues/keymap"]
compositor = "mangowc"
mangowc_config = "/home/sh4dow/.config/mango/mango-config/bind.conf"

[plugin_settings."noctalia/mpvpaper"]
video_directory = "~/Videos"

[plugin_settings."noctalia/wallhaven"]
browser_open_near_click = true
download_dir = "/home/sh4dow/Pictures/wallpapers"

[plugin_settings."yuuto/arch-updater"]
aur_helper = "yay"

[plugins]
enabled = ["noctalia/wallhaven", "dotnetrob/cat", "alexmnrs/github-activity"]

[[plugins.source]]
auto_update = true
kind = "git"
location = "https://github.com/noctalia-dev/official-plugins"
name = "official"

[[plugins.source]]
auto_update = true
kind = "git"
location = "https://github.com/noctalia-dev/community-plugins"
name = "community"

[[plugins.source]]
enabled = false
kind = "git"
location = "https://github.com/noctalia-dev/community-plugins.git"
name = "community-plugins"

[shell]
app_icon_colorize = false
avatar_path = "/home/sh4dow/Pictures/Pics/boy.jpg"
button_borders = false
card_borders = false
corner_radius_scale = 2.0
font_family = "JetBrainsMono NFM"
input_borders = false
polkit_agent = true
popup_borders = false
settings_show_advanced = true
show_location = false
ui_scale = 0.90000000596046448

[shell.panel]
borders = false
clipboard_placement = "attached"
launcher_placement = "attached"
polkit_placement = "attached"

[shell.screen_corners]
size = 1

[templates.nvim-base16]
input_path = "~/.config/nvim/lua/matugen-template.lua"
output_path = "~/.config/nvim/lua/matugen.lua"
post_hook = "pkill -SIGUSR1 nvim"

[theme]
builtin = "Rosé Pine"
community_palette = "Aura"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-content"

[theme.templates]
builtin_ids = [
  "alacritty",
  "gtk3",
  "gtk4",
  "ghostty",
  "mango",
  "qt",
  "starship",
]
community_ids = [
  "libreoffice",
  "obsidian",
  "zed",
  "rofi",
  "fastfetch",
  "lazygit",
]
enable_builtin_templates = true
enable_community_templates = true

[theme.templates.litexl]
input_path = "/home/sh4dow/.config/noctalia/templates/lite-xl.lua"
output_path = "~/.config/lite-xl/colors/matugen.lua"

[theme.templates.rmpc]
input_path = "/home/sh4dow/.config/noctalia/templates/rmpc.ron"
output_path = "~/.config/rmpc/themes/matugen.ron"

[theme.templates.rofi]
input_path = "/home/sh4dow/.config/noctalia/templates/rofi-colors.rasi"
output_path = "/home/sh4dow/.config/rofi/colors.rasi"

[wallpaper]
directory = "/home/sh4dow/Pictures/wallpapers"
transition_on_startup = true

[wallpaper.automation]
enabled = true
interval_seconds = 300

[wallpaper.default]
path = "/home/sh4dow/Pictures/wallpapers/hollow-knight.jpg"

[wallpaper.last]
path = "/home/sh4dow/Pictures/wallpapers/hollow-knight.jpg"

[wallpaper.monitors.eDP-1]
path = "/home/sh4dow/Pictures/wallpapers/hollow-knight.jpg"

[weather]
enabled = false

[widget.activity]
type = "alexmnrs/github-activity:activity"

[widget.cat]
type = "dotnetrob/cat:cat"

[widget.clock]
format = "{:%I:%M %p}"

[widget.mpvpaper]
type = "noctalia/mpvpaper:mpvpaper"

[widget.network]
show_label = false

[widget.wallhaven]
type = "noctalia/wallhaven:wallhaven"

[widget.workspaces]
hide_when_empty = true
scale = 0.90000000000000002
