[theme.templates]
enable_builtin_templates = true
enable_community_templates = true
builtin_ids = []
community_ids = []


[theme.templates.rmpc]
input_path = '/home/sh4dow/.config/noctalia/templates/rmpc.ron'
output_path = '~/.config/rmpc/themes/matugen.ron'
