# : Manager [[[

[mgr]
cwd = { fg = "#c0c0c0" }

# Find
find_keyword  = { fg = "#ff6a5d", bold = true, italic = true, underline = true }
find_position = { fg = "#ff6a5d", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#837da5", bg = "#837da5" }
marker_cut      = { fg = "#524d6f", bg = "#524d6f" }
marker_marked   = { fg = "#ff6a5d", bg = "#ff6a5d" }
marker_selected = { fg = "#9c96bc", bg = "#9c96bc" }

# Count
count_copied   = { fg = "#e8e1ff", bg = "#524d6f" }
count_cut      = { fg = "#e8e1ff", bg = "#524d6f" }
count_selected = { fg = "#002231", bg = "#9c96bc" }

# Border
border_symbol = "│"
border_style  = { fg = "#76d1ff" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#30a5d5", bold = true, bg = "#131313" }
inactive  = { fg = "#899daa", bg = "#131313" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#30a5d5", fg = "#002231", bold = true }
normal_alt  = { bg = "#474747", fg = "#9a9a9a" }

# Select mode
select_main = { bg = "#899daa", fg = "#061b24", bold = true }
select_alt  = { bg = "#474747", fg = "#9a9a9a" }

# Unset mode
unset_main = { bg = "#9c96bc", fg = "#181432", bold = true }
unset_alt  = { bg = "#474747", fg = "#9a9a9a" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#40505a" }
perm_write = { fg = "#4f4871" }
perm_read  = { fg = "#c31000" }
perm_exec  = { fg = "#a09bba" }
perm_sep   = { fg = "#10c2ff" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#30a5d5", bg = "#393939" }
progress_error  = { fg = "#ff6a5d", bg = "#393939" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#393939" }
cand = { fg = "#30a5d5" }
rest = { fg = "#002231" }
desc = { fg = "#c0c0c0" }
separator = " ▶ "
separator_style = { fg = "#c0c0c0" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#9c96bc" }
title_warn  = { fg = "#30a5d5" }
title_error = { fg = "#ff6a5d" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#30a5d5" }
active = { fg = "#9c96bc", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#30a5d5" }
value  = { fg = "#c0c0c0" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#30a5d5", bg = "#002231" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#30a5d5" }
title   = {}
hovered = { fg = "#524d6f", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#c0c0c0" }
run    = { fg = "#c0c0c0" }
footer = { fg = "#061b24", bg = "#899daa" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#7b0007" },
    { name = "*", is = "exec", fg = "#ffaca2" },

    # Fallback
    { url = "*", fg = "#c0c0c0" },
    { url = "*/", fg = "#76d1ff" },
]

# : ]]]
