# : Manager [[[

[mgr]
cwd = { fg = "#dfe4dc" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#7ca27a", bg = "#7ca27a" }
marker_cut      = { fg = "#b7ccb6", bg = "#b7ccb6" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#b7ccb6", bg = "#b7ccb6" }

# Count
count_copied   = { fg = "#003916", bg = "#b7ccb6" }
count_cut      = { fg = "#003916", bg = "#b7ccb6" }
count_selected = { fg = "#003916", bg = "#b7ccb6" }

# Border
border_symbol = "│"
border_style  = { fg = "#9ad4a1" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#9ad4a1", bold = true, bg = "#101510" }
inactive  = { fg = "#b7ccb6", bg = "#101510" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#9ad4a1", fg = "#003916", bold = true }
normal_alt  = { bg = "#101510", fg = "#c1c9be" }

# Select mode
select_main = { bg = "#b7ccb6", fg = "#003916", bold = true }
select_alt  = { bg = "#101510", fg = "#c1c9be" }

# Unset mode
unset_main = { bg = "#b7ccb6", fg = "#003916", bold = true }
unset_alt  = { bg = "#101510", fg = "#c1c9be" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#628960" }
perm_write = { fg = "#628960" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#628960" }
perm_sep   = { fg = "#48a856" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#9ad4a1", bg = "#222822" }
progress_error  = { fg = "#ffb4ab", bg = "#222822" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#222822" }
cand = { fg = "#9ad4a1" }
rest = { fg = "#003916" }
desc = { fg = "#dfe4dc" }
separator = " ▶ "
separator_style = { fg = "#dfe4dc" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#b7ccb6" }
title_warn  = { fg = "#9ad4a1" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#9ad4a1" }
active = { fg = "#b7ccb6", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#9ad4a1" }
value  = { fg = "#dfe4dc" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#9ad4a1", bg = "#003916" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#9ad4a1" }
title   = {}
hovered = { fg = "#b7ccb6", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#dfe4dc" }
run    = { fg = "#dfe4dc" }
footer = { fg = "#003916", bg = "#b7ccb6" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#8c1d18" },
    { name = "*", is = "exec", fg = "#f9dedc" },

    # Fallback
    { url = "*", fg = "#dfe4dc" },
    { url = "*/", fg = "#9ad4a1" },
]

# : ]]]
