# : Manager [[[

[mgr]
cwd = { fg = "#cdd6f4" }

# Find
find_keyword  = { fg = "#f2b8b5", bold = true, italic = true, underline = true }
find_position = { fg = "#f2b8b5", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#aa717b", bg = "#aa717b" }
marker_cut      = { fg = "#71444c", bg = "#71444c" }
marker_marked   = { fg = "#f2b8b5", bg = "#f2b8b5" }
marker_selected = { fg = "#bf8991", bg = "#bf8991" }

# Count
count_copied   = { fg = "#0d0e14", bg = "#71444c" }
count_cut      = { fg = "#0d0e14", bg = "#71444c" }
count_selected = { fg = "#0d0e14", bg = "#bf8991" }

# Border
border_symbol = "│"
border_style  = { fg = "#d8bafa" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#cba6f7", bold = true, bg = "#181920" }
inactive  = { fg = "#9f93aa", bg = "#181920" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#cba6f7", fg = "#0d0e14", bold = true }
normal_alt  = { bg = "#1e1f2b", fg = "#bac2de" }

# Select mode
select_main = { bg = "#9f93aa", fg = "#0d0e14", bold = true }
select_alt  = { bg = "#1e1f2b", fg = "#bac2de" }

# Unset mode
unset_main = { bg = "#bf8991", fg = "#0d0e14", bold = true }
unset_alt  = { bg = "#1e1f2b", fg = "#bac2de" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#52485c" }
perm_write = { fg = "#713e45" }
perm_read  = { fg = "#db3b33" }
perm_exec  = { fg = "#bd9199" }
perm_sep   = { fg = "#ab97c5" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#cba6f7", bg = "#282936" }
progress_error  = { fg = "#f2b8b5", bg = "#282936" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#282936" }
cand = { fg = "#cba6f7" }
rest = { fg = "#0d0e14" }
desc = { fg = "#cdd6f4" }
separator = " ▶ "
separator_style = { fg = "#cdd6f4" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#bf8991" }
title_warn  = { fg = "#cba6f7" }
title_error = { fg = "#f2b8b5" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#cba6f7" }
active = { fg = "#bf8991", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#cba6f7" }
value  = { fg = "#cdd6f4" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#cba6f7", bg = "#0d0e14" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#cba6f7" }
title   = {}
hovered = { fg = "#71444c", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#cdd6f4" }
run    = { fg = "#cdd6f4" }
footer = { fg = "#0d0e14", bg = "#9f93aa" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#8c1d18" },
    { name = "*", is = "exec", fg = "#f9dedc" },

    # Fallback
    { url = "*", fg = "#cdd6f4" },
    { url = "*/", fg = "#d8bafa" },
]

# : ]]]
